apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - web-pvc.yaml
  - web-deployment.yaml
  - web-service.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
