apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# "base" contains generic manifests that work everywhere.
resources:
  - namespace.yaml
  - web-deployment.yaml
  - web-service.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
