name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:  # roƒçni zagon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hodzaarmen
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: ./ToDo
          file: ./ToDo/Dockerfile
          push: true
          tags: ghcr.io/hodzaarmen/todo-web:latest
          cache-from: type=registry,ref=ghcr.io/hodzaarmen/todo-web:latest
          cache-to: type=inline

      - name: Build and push worker image
        uses: docker/build-push-action@v4
        with:
          context: ./ToDo
          file: ./ToDo/Dockerfile
          push: true
          tags: ghcr.io/hodzaarmen/todo-worker:latest
          cache-from: type=registry,ref=ghcr.io/hodzaarmen/todo-worker:latest
          cache-to: type=inline
